version: '2'
services:
    starter-app:
        image: starter
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://starter-mysql:3306/starter?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=starter-elasticsearch:9300
        ports:
            - 8080:8080
    starter-mysql:
        extends:
            file: mysql.yml
            service: starter-mysql
    starter-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: starter-elasticsearch
